# Generated by Django 4.2.7 on 2024-02-06 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Todos',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('todo_name', models.CharField()),
                ('description', models.TextField()),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'todos',
                'managed': True,
            },
        ),
    ]
