# Generated by Django 4.2.7 on 2024-02-07 02:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_todos'),
    ]

    operations = [
        migrations.AddField(
            model_name='todos',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='todo.authuser'),
        ),
    ]
